const CONFIG = {
  SPREADSHEET_ID: '1UB_oVX-V_GXjuwmgP6u9DybpaPcaEThhBMOprPpPHFQ',
  DRIVE_ROOT_FOLDER_ID: '197iqHWkSoFRKYKrckPhhTfLvuctBhMg_',
  TIMEZONE: 'America/Sao_Paulo',
  CHUVA_THRESHOLD_MM: 5
};

