const CONFIG = {
  SPREADSHEET_ID: '1UB_oVX-V_GXjuwmgP6u9DybpaPcaEThhBMOprPpPHFQ',
  DRIVE_ROOT_FOLDER_ID: '1OzzU822EbjFaUnR17DDu8MdJMWp5QVhm',
  TIMEZONE: 'America/Sao_Paulo',
  CHUVA_THRESHOLD_MM: 5,
  WHATSAPP_PCU: {
    ENABLED: false,
    CONFIGURED: false,
    MESSAGES_SENT: 0,
    ESTIMATED_MESSAGES_AVAILABLE: 1000,
    ESTIMATED_CREDIT_BRL: 34
  }
};

